version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:5000" 
    volumes:
      - ./app:/app/app
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - FLASK_APP=app.main
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - MODEL_SERVICE_URL=http://model:5001
    depends_on:
      - model
    command: flask run --host=0.0.0.0

  model:
    build:
      context: .
      dockerfile: model.Dockerfile
    volumes:
      - ./models:/app/models
      - ./extractors:/app/extractors
    expose:
      - "5001"