name: Docker Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and export web image
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: clinical-protocol-engine-web:test
          load: true
          
      - name: Build and export model image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: model.Dockerfile
          tags: clinical-protocol-engine-model:test
          load: true
          
      - name: Test images
        run: |
          docker images
          echo "Docker images built successfully!"